name: Deploy Evolution API to Railway

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: # Definir o RAILWAY_TOKEN no nível do JOB para que todos os passos o herdem
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          # A linha de login explícito foi removida daqui, pois o token no env do job deve ser suficiente

      - name: Deploy to Railway
        # O RAILWAY_TOKEN já está no ambiente deste passo devido ao 'env:' no nível do job
        run: |
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          railway up --yes

      - name: Set Environment Variables
        # O RAILWAY_TOKEN já está no ambiente deste passo
        run: |
          railway env set SERVER_TYPE=http
          railway env set SERVER_PORT=8080
          railway env set CORS_ORIGIN=*
          railway env set DATABASE_ENABLED=true
          railway env set DATABASE_PROVIDER=postgresql
          railway env set DATABASE_CONNECTION_URI=${{ secrets.DATABASE_URL }}
          railway env set AUTHENTICATION_API_KEY=${{ secrets.EVO_API_KEY }}
